apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hpc-ai-demo
  region: us-east-2
  version: "1.28"

iam:
  withOIDC: true

managedNodeGroups: []

nodeGroups:
  - name: ng-1
    instanceType: t4g.2xlarge
    desiredCapacity: 1
    volumeSize: 100
    iam:
      withAddonPolicies:
        ebs: true
    ssh:
      allow: true
      publicKeyName: hpc-ai-demo-ec2

addons:
  - name: aws-ebs-csi-driver
    wellKnownPolicies:
      ebsCSIController: true
  - name: kube-proxy
  - name: coredns
